In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../raw_data/congress_tweets/congresstweets-automator/data/users-filtered.json", encoding='utf-8')

In [3]:
df.head()

,accounts,chamber,id,name,party,state,type
0,"{'office': [{'id': 817097052375187500, 'id_str...",house,NaN,Blue Collar Caucus,D,NaN,caucus
1,"{'office': [{'id': 224685124, 'id_str': '22468...",house,NaN,Blue Dog Coalition,D,NaN,caucus
2,"{'office': [{'id': 192955168, 'id_str': '19295...",house,NaN,Congressional Asian Pacific American Caucus,D,NaN,caucus
3,"{'office': [{'id': 233783568, 'id_str': '23378...",house,NaN,Congressional Black Caucus,D,NaN,caucus
4,"{'office': [{'id': 20020575, 'id_str': '200205...",house,NaN,Congressional Health Caucus,R,NaN,caucus

In [4]:
df.to_csv('meta_raw.csv', encoding='utf-8')

In [5]:
df1 = df[df['type'] == "committee"]

In [6]:
party = pd.read_csv('party.csv', encoding='utf-8')

In [7]:
party.drop('Unnamed: 0', 1, inplace=True)

In [8]:
df = df[df['type'] != "committee"]

In [9]:
df = df[df['type'] != "party"]

In [10]:
df1.reset_index(drop=True, inplace=True)

In [11]:
df1.to_csv('committee.csv', index=False, encoding='utf-8')

In [12]:
df1.head()

,accounts,chamber,id,name,party,state,type
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,NaN,committee
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,NaN,committee
2,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,NaN,committee
3,"{'office': [{'id': 7004382, 'id_str': '7004382...",house,"{'thomas_id': 'HSED', 'house_committee_id': 'E...",House Committee on Education and the Workforce,NaN,NaN,committee
4,"{'office': [{'id': 30929600, 'id_str': '309296...",house,"{'thomas_id': 'HSIF', 'house_committee_id': 'I...",House Committee on Energy and Commerce,NaN,NaN,committee

In [13]:
count = 0

for x in df1.accounts:
    x['index'] = count
    count = count + 1

In [14]:
df1.loc[1,'accounts']

{'index': 1,
 'office': [{'id': 30912937,
   'id_str': '30912937',
   'party': 'D',
   'screen_name': 'AppropsDems'},
  {'id': 301549400,
   'id_str': '301549400',
   'party': 'R',
   'screen_name': 'HouseAppropsGOP'}]}

In [15]:
comm = []

for x in df1.accounts:
    if len(x['office']) == 1:
        comm.append([x['index'], x['office'][0]['party'], x['office'][0]['screen_name']])
    else:
        comm.append([x['index'], x['office'][0]['party'], x['office'][0]['screen_name']])
        comm.append([x['index'], x['office'][1]['party'], x['office'][1]['screen_name']])

In [16]:
df1['index'] = df1.index

In [17]:
df2 = pd.DataFrame(comm, columns = ['index', 'party1', 'screen_name'])

In [18]:
df2.head()

   index party1      screen_name
0      0      R      HouseAgNews
1      1      D      AppropsDems
2      1      R  HouseAppropsGOP
3      2      D    HASCDemocrats
4      2      R  HASCRepublicans

In [19]:
df1.head()

,accounts,chamber,id,name,party,state,type,index
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,NaN,committee,0
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,NaN,committee,1
2,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,NaN,committee,2
3,"{'office': [{'id': 7004382, 'id_str': '7004382...",house,"{'thomas_id': 'HSED', 'house_committee_id': 'E...",House Committee on Education and the Workforce,NaN,NaN,committee,3
4,"{'office': [{'id': 30929600, 'id_str': '309296...",house,"{'thomas_id': 'HSIF', 'house_committee_id': 'I...",House Committee on Energy and Commerce,NaN,NaN,committee,4

In [20]:
df2.head()

   index party1      screen_name
0      0      R      HouseAgNews
1      1      D      AppropsDems
2      1      R  HouseAppropsGOP
3      2      D    HASCDemocrats
4      2      R  HASCRepublicans

In [21]:
df1 = pd.DataFrame.merge(df1, df2, how="left", on='index')

In [22]:
df1.head()

,accounts,chamber,id,name,party,state,type,index,party1,screen_name
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,NaN,committee,0,R,HouseAgNews
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,NaN,committee,1,D,AppropsDems
2,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,NaN,committee,1,R,HouseAppropsGOP
3,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,NaN,committee,2,D,HASCDemocrats
4,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,NaN,committee,2,R,HASCRepublicans

In [23]:
df1.shape

(55, 10)

In [24]:
df1.drop('party', 1, inplace=True)

In [25]:
df1.drop(['index'], 1, inplace=True)

In [26]:
df1.rename(columns={'party1': 'party'}, inplace=True)

In [27]:
df1.head()

,accounts,chamber,id,name,state,type,party,screen_name
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,committee,R,HouseAgNews
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,D,AppropsDems
2,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,R,HouseAppropsGOP
3,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,D,HASCDemocrats
4,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,R,HASCRepublicans

In [28]:
df.shape

(552, 7)

In [29]:
df.head()

,accounts,chamber,id,name,party,state,type
0,"{'office': [{'id': 817097052375187500, 'id_str...",house,NaN,Blue Collar Caucus,D,NaN,caucus
1,"{'office': [{'id': 224685124, 'id_str': '22468...",house,NaN,Blue Dog Coalition,D,NaN,caucus
2,"{'office': [{'id': 192955168, 'id_str': '19295...",house,NaN,Congressional Asian Pacific American Caucus,D,NaN,caucus
3,"{'office': [{'id': 233783568, 'id_str': '23378...",house,NaN,Congressional Black Caucus,D,NaN,caucus
4,"{'office': [{'id': 20020575, 'id_str': '200205...",house,NaN,Congressional Health Caucus,R,NaN,caucus

In [30]:
count = 0

for x in df.accounts:
    x['index'] = count
    count = count + 1

In [31]:
df.reset_index(inplace=True, drop=True)

In [32]:
handles = []


for item in df.accounts:
    if 'office' in item.keys() and 'campaign' in item.keys():
        if len(item['office']) > 1 and len(item['campaign']) > 1:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
            handles.append([item['index'], item['office'][1]['screen_name'], 'no'])
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
            handles.append([item['index'], item['campaign'][1]['screen_name'], 'yes'])
        elif len(item['office']) > 1 and len(item['campaign']) == 1:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
            handles.append([item['index'], item['office'][1]['screen_name'], 'no'])
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
        elif len(item['office']) == 1 and len(item['campaign']) > 1:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
            handles.append([item['index'], item['campaign'][1]['screen_name'], 'yes'])
        elif len(item['office']) == 1 and len(item['campaign']) == 1:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
        elif len(item['office']) == 0 and len(item['campaign']) == 1:
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
        elif len(item['office']) == 1 and len(item['campaign']) == 0:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
    elif 'office' in item.keys():
        if len(item['office']) > 1:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
            handles.append([item['index'], item['office'][1]['screen_name'], 'no'])
        else:
            handles.append([item['index'], item['office'][0]['screen_name'], 'no'])
    else:
        if len(item['campaign']) > 1:
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
            handles.append([item['index'], item['campaign'][1]['screen_name'], 'yes'])
        else:
            handles.append([item['index'], item['campaign'][0]['screen_name'], 'yes'])
        
len(handles)

1007

In [33]:
df6 = pd.DataFrame(handles, columns = ['index', 'screen_name', 'ch'])

In [34]:
df6.shape

(1007, 3)

In [35]:
df.head()

,accounts,chamber,id,name,party,state,type
0,"{'office': [{'id': 817097052375187500, 'id_str...",house,NaN,Blue Collar Caucus,D,NaN,caucus
1,"{'office': [{'id': 224685124, 'id_str': '22468...",house,NaN,Blue Dog Coalition,D,NaN,caucus
2,"{'office': [{'id': 192955168, 'id_str': '19295...",house,NaN,Congressional Asian Pacific American Caucus,D,NaN,caucus
3,"{'office': [{'id': 233783568, 'id_str': '23378...",house,NaN,Congressional Black Caucus,D,NaN,caucus
4,"{'office': [{'id': 20020575, 'id_str': '200205...",house,NaN,Congressional Health Caucus,R,NaN,caucus

In [36]:
df['index'] = df.index
df.head()

,accounts,chamber,id,name,party,state,type,index
0,"{'office': [{'id': 817097052375187500, 'id_str...",house,NaN,Blue Collar Caucus,D,NaN,caucus,0
1,"{'office': [{'id': 224685124, 'id_str': '22468...",house,NaN,Blue Dog Coalition,D,NaN,caucus,1
2,"{'office': [{'id': 192955168, 'id_str': '19295...",house,NaN,Congressional Asian Pacific American Caucus,D,NaN,caucus,2
3,"{'office': [{'id': 233783568, 'id_str': '23378...",house,NaN,Congressional Black Caucus,D,NaN,caucus,3
4,"{'office': [{'id': 20020575, 'id_str': '200205...",house,NaN,Congressional Health Caucus,R,NaN,caucus,4

In [37]:
df7 = pd.DataFrame.merge(df6, df, how='left', on='index')

In [38]:
df7.head()

,index,screen_name,ch,accounts,chamber,id,name,party,state,type
0,0,BlueCollarDems,no,"{'office': [{'id': 817097052375187500, 'id_str...",house,NaN,Blue Collar Caucus,D,NaN,caucus
1,1,HouseBlueDogs,no,"{'office': [{'id': 224685124, 'id_str': '22468...",house,NaN,Blue Dog Coalition,D,NaN,caucus
2,2,CAPAC,no,"{'office': [{'id': 192955168, 'id_str': '19295...",house,NaN,Congressional Asian Pacific American Caucus,D,NaN,caucus
3,3,OfficialCBC,no,"{'office': [{'id': 233783568, 'id_str': '23378...",house,NaN,Congressional Black Caucus,D,NaN,caucus
4,4,HealthCaucus,no,"{'office': [{'id': 20020575, 'id_str': '200205...",house,NaN,Congressional Health Caucus,R,NaN,caucus

In [39]:
df1.head()

,accounts,chamber,id,name,state,type,party,screen_name
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,committee,R,HouseAgNews
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,D,AppropsDems
2,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,R,HouseAppropsGOP
3,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,D,HASCDemocrats
4,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,R,HASCRepublicans

In [40]:
df1['ch'] = 'no'

In [41]:
df1.head()

,accounts,chamber,id,name,state,type,party,screen_name,ch
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,committee,R,HouseAgNews,no
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,D,AppropsDems,no
2,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,R,HouseAppropsGOP,no
3,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,D,HASCDemocrats,no
4,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,R,HASCRepublicans,no

In [42]:
df7.drop('index', 1, inplace=True)

In [43]:
party.head()

,screen_name,accounts,chamber,id,name,party,state,type,ch
0,DemCloakroom,"{u'index': 0, u'campaign': [{u'screen_name': u...",house,NaN,Democrats,D,NaN,party,yes
1,HouseDemocrats,"{u'index': 0, u'campaign': [{u'screen_name': u...",house,NaN,Democrats,D,NaN,party,no
2,dccc,"{u'index': 0, u'campaign': [{u'screen_name': u...",house,NaN,Democrats,D,NaN,party,yes
3,GOPEspanol,"{u'index': 1, u'campaign': [{u'screen_name': u...",house,NaN,Republicans,R,NaN,party,no
4,GOPpolicy,"{u'index': 1, u'campaign': [{u'screen_name': u...",house,NaN,Republicans,R,NaN,party,no

In [44]:
df1

,accounts,chamber,id,name,state,type,party,screen_name,ch
0,"{'office': [{'id': 234573331, 'id_str': '23457...",house,"{'thomas_id': 'HSAG', 'house_committee_id': 'A...",House Committee on Agriculture,NaN,committee,R,HouseAgNews,no
1,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,D,AppropsDems,no
2,"{'office': [{'id': 30912937, 'id_str': '309129...",house,"{'thomas_id': 'HSAP', 'house_committee_id': 'A...",House Committee on Appropriations,NaN,committee,R,HouseAppropsGOP,no
3,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,D,HASCDemocrats,no
4,"{'office': [{'id': 74294786, 'id_str': '742947...",house,"{'thomas_id': 'HSAS', 'house_committee_id': 'A...",House Committee on Armed Services,NaN,committee,R,HASCRepublicans,no
5,"{'office': [{'id': 7004382, 'id_str': '7004382...",house,"{'thomas_id': 'HSED', 'house_committee_id': 'E...",House Committee on Education and the Workforce,NaN,committee,D,edworkforcedems,no
6,"{'office': [{'id': 7004382, 'id_str': '7004382...",house,"{'thomas_id': 'HSED', 'house_committee_id': 'E...",House Committee on Education and the Workforce,NaN,committee,R,EdWorkforce,no
7,"{'office': [{'id': 30929600, 'id_str': '309296...",house,"{'thomas_id': 'HSIF', 'house_committee_id': 'I...",House Committee on Energy and Commerce,NaN,committee,D,EnergyCommerce,no
8,"{'office': [{'id': 30929600, 'id_str': '309296...",house,"{'thomas_id': 'HSIF', 'house_committee_id': 'I...",House Committee on Energy and Commerce,NaN,committee,R,HouseCommerce,no
9,"{'office': [{'id': 294084341, 'id_str': '29408...",house,"{'thomas_id': 'HSBA', 'house_committee_id': 'B...",House Committee on Financial Services,NaN,committee,D,FSCDems,no
10,"{'office': [{'id': 294084341, 'id_str': '29408...",house,"{'thomas_id': 'HSBA', 'house_committee_id': 'B...",House Committee on Financial Services,NaN,committee,R,FinancialCmte,no
11,"{'office': [{'id': 61206798, 'id_str': '612067...",house,"{'thomas_id': 'HSFA', 'house_committee_id': 'F...",House Committee on Foreign Affairs,NaN,committee,D,HFACDemocrats,no
12,"{'office': [{'id': 61206798, 'id_str': '612067...",house,"{'thomas_id': 'HSFA', 'house_committee_id': 'F...",House Committee on Foreign Affairs,NaN,committee,R,HouseForeign,no
13,"{'office': [{'id': 208692908, 'id_str': '20869...",house,"{'thomas_id': 'HSHM', 'house_committee_id': 'H...",House Committee on Homeland Security,NaN,committee,D,HomelandDems,no
14,"{'office': [{'id': 208692908, 'id_str': '20869...",house,"{'thomas_id': 'HSHM', 'house_committee_id': 'H...",House Committee on Homeland Security,NaN,committee,R,HouseHomeland,no
15,"{'office': [{'id': 19716781, 'id_str': '197167...",house,"{'thomas_id': 'HSHA', 'house_committee_id': 'H...",House Committee on House Administration,NaN,committee,D,HouseAdm_Dems,no
16,"{'office': [{'id': 19716781, 'id_str': '197167...",house,"{'thomas_id': 'HSHA', 'house_committee_id': 'H...",House Committee on House Administration,NaN,committee,R,HouseAdmnGOP,no
17,"{'office': [{'id': 247486443, 'id_str': '24748...",house,"{'thomas_id': 'HSII', 'house_committee_id': 'I...",House Committee on Natural Resources,NaN,committee,D,NRDems,no
18,"{'office': [{'id': 247486443, 'id_str': '24748...",house,"{'thomas_id': 'HSII', 'house_committee_id': 'I...",House Committee on Natural Resources,NaN,committee,R,NatResources,no
19,"{'office': [{'id': 31122582, 'id_str': '311225...",house,"{'thomas_id': 'HSGO', 'house_committee_id': 'G...",House Committee on Oversight and Government Re...,NaN,committee,D,OversightDems,no
20,"{'office': [{'id': 31122582, 'id_str': '311225...",house,"{'thomas_id': 'HSGO', 'house_committee_id': 'G...",House Committee on Oversight and Government Re...,NaN,committee,R,GOPoversight,no
21,"{'office': [{'id': 78369108, 'id_str': '783691...",house,"{'thomas_id': 'HSRU', 'house_committee_id': 'R...",House Committee on Rules,NaN,committee,R,RulesReps,no
22,"{'office': [{'id': 22053641, 'id_str': '220536...",house,"{'thomas_id': 'HSSY', 'house_committee_id': 'S...","House Committee on Science, Space, and Technology",NaN,committee,D,SciCmteDems,no
23,"{'office': [{'id': 22053641, 'id_str': '220536...",house,"{'thomas_id': 'HSSY', 'house_committee_id': 'S...","House Committee on Science, Space, and Technology",NaN,committee,R,HouseScience,no
24,"{'office': [{'id': 2978291435, 'id_str': '2978...",house,"{'thomas_id': 'HSSM', 'house_committee_id': 'S...",House Committee on Small Business,NaN,committee,R,HouseSmallBiz,no
25,"{'office': [{'id': 21684013, 'id_str': '216840...",house,"{'thomas_id': 'HSPW', 'house_committee_id': 'P...",House Committee on Transportation and Infrastr...,NaN,committee,D,TransportDems,no
26,"{'office': [{'id': 21684013, 'id_str': '216840...",house,"{'thomas_id': 'HSPW', 'house_committee_id': 'P...",House Committee on Transportation and Infrastr...,NaN,committee,R,Transport,no
27,"{'office': [{'id': 151519500, 'id_str': '15151...",house,"{'thomas_id': 'HSVR', 'house_committee_id': 'V...",House Committee on Veterans' Affairs,NaN,committee,D,VetAffairsDems,no
28,"{'office': [{'id': 151519500, 'id_str': '15151...",house,"{'thomas_id': 'HSVR', 'house_committee_id': 'V...",House Committee on Veterans' Affairs,NaN,committee,R,HouseVetAffairs,no
29,"{'office': [{'id': 31128529, 'id_str': '311285...",house,"{'thomas_id': 'HSWM', 'house_committee_id': 'W...",House Committee on Ways and Means,NaN,committee,D,WaysMeansCmte,no
30,"{'office': [{'id': 31128529, 'id_str': '311285...",house,"{'thomas_id': 'HSWM', 'house_committee_id': 'W...",House Committee on Ways and Means,NaN,committee,R,WaysandMeansGOP,no
31,"{'office': [{'id': 151963505, 'id_str': '15196...",house,"{'thomas_id': 'HSBU', 'house_committee_id': 'B...",House Committee on the Budget,NaN,committee,D,HouseBudgetDems,no
32,"{'office': [{'id': 151963505, 'id_str': '15196...",house,"{'thomas_id': 'HSBU', 'house_committee_id': 'B...",House Committee on the Budget,NaN,committee,R,housebudgetGOP,no
33,"{'office': [{'id': 246357149, 'id_str': '24635...",house,"{'thomas_id': 'HSJU', 'house_committee_id': 'J...",House Committee on the Judiciary,NaN,committee,D,HouseJudDems,no
34,"{'office': [{'id': 246357149, 'id_str': '24635...",house,"{'thomas_id': 'HSJU', 'house_committee_id': 'J...",House Committee on the Judiciary,NaN,committee,R,HouseJudiciary,no
35,"{'office': [{'id': 2864316239, 'id_str': '2864...",joint,"{'thomas_id': 'JSTX', 'senate_committee_id': '...",Joint Committee on Taxation,NaN,committee,N/A,jctgov,no
36,"{'office': [{'id': 116505994, 'id_str': '11650...",joint,"{'thomas_id': 'JSEC', 'senate_committee_id': '...",Joint Economic Committee,NaN,committee,D,JECDems,no
37,"{'office': [{'id': 116505994, 'id_str': '11650...",joint,"{'thomas_id': 'JSEC', 'senate_committee_id': '...",Joint Economic Committee,NaN,committee,R,JECRepublicans,no
38,"{'office': [{'id': 3006258669, 'id_str': '3006...",senate,"{'thomas_id': 'SSAS21F', 'senate_committee_id'...","Senate Committee on Agriculture, Nutrition, an...",NaN,committee,R,SenateAgGOP,no
39,"{'office': [{'id': 352534407, 'id_str': '35253...",senate,"{'thomas_id': 'SSAP', 'senate_committee_id': '...",Senate Committee on Appropriations,NaN,committee,D,SenateApprops,no
40,"{'office': [{'id': 275572403, 'id_str': '27557...",senate,"{'thomas_id': 'SSAS', 'senate_committee_id': '...",Senate Committee on Armed Services,NaN,committee,R,SASCMajority,no
41,"{'office': [{'id': 1242040290, 'id_str': '1242...",senate,"{'thomas_id': 'SSBK', 'senate_committee_id': '...","Senate Committee on Banking, Housing, and Urba...",NaN,committee,R,BankingGOP,no
42,"{'office': [{'id': 386092483, 'id_str': '38609...",senate,"{'thomas_id': 'SSCM', 'senate_committee_id': '...","Senate Committee on Commerce, Science, and Tra...",NaN,committee,R,SenateCommerce,no
43,"{'office': [{'id': 277124730, 'id_str': '27712...",senate,"{'thomas_id': 'SSEG', 'senate_committee_id': '...",Senate Committee on Energy and Natural Resources,NaN,committee,D,EnergyDems,no
44,"{'office': [{'id': 277124730, 'id_str': '27712...",senate,"{'thomas_id': 'SSEG', 'senate_committee_id': '...",Senate Committee on Energy and Natural Resources,NaN,committee,R,EnergyGOP,no
45,"{'office': [{'id': 245891006, 'id_str': '24589...",senate,"{'thomas_id': 'SSEV', 'senate_committee_id': '...",Senate Committee on Environment and Public Works,NaN,committee,D,EPWDems,no
46,"{'office': [{'id': 245891006, 'id_str': '24589...",senate,"{'thomas_id': 'SSEV', 'senate_committee_id': '...",Senate Committee on Environment and Public Works,NaN,committee,R,EPWGOP,no
47,"{'office': [{'id': 701821488, 'id_str': '70182...",senate,"{'thomas_id': 'SSFI', 'senate_committee_id': '...",Senate Committee on Finance,NaN,committee,R,GOPSenFinance,no
48,"{'office': [{'id': 292972175, 'id_str': '29297...",senate,"{'thomas_id': 'SSHR', 'senate_committee_id': '...","Senate Committee on Health, Education, Labor, ...",NaN,committee,R,GOPHELP,no
49,"{'office': [{'id': 329761746, 'id_str': '32976...",senate,"{'thomas_id': 'SLIA', 'senate_committee_id': '...",Senate Committee on Indian Affairs,NaN,committee,R,IndianCommittee,no
50,"{'office': [{'id': 2932401927, 'id_str': '2932...",senate,"{'thomas_id': 'SSSB', 'senate_committee_id': '...",Senate Committee on Small Business and Entrepr...,NaN,committee,R,SmallBizCmte,no
51,"{'office': [{'id': 1009054656, 'id_str': '1009...",senate,"{'thomas_id': 'SSVA', 'senate_committee_id': '...",Senate Committee on Veterans' Affairs,NaN,committee,R,VAChair,no
52,"{'office': [{'id': 2992440550, 'id_str': '2992...",senate,"{'thomas_id': 'SSBU', 'senate_committee_id': '...",Senate Committee on the Budget,NaN,committee,R,BudgetGOP,no
53,"{'office': [{'id': 704320143824953300, 'id_str...",senate,"{'thomas_id': 'SSJU', 'senate_committee_id': '...",Senate Committee on the Judiciary,NaN,committee,R,senjudiciary,no
54,"{'office': [{'id': 2359937696, 'id_str': '2359...",senate,"{'thomas_id': 'SPAG', 'senate_committee_id': '...",Senate Special Committee on Aging,NaN,committee,R,SenateAging,no

In [45]:
df7

,screen_name,ch,accounts,chamber,id,name,party,state,type
0,BlueCollarDems,no,"{'office': [{'id': 817097052375187500, 'id_str...",house,NaN,Blue Collar Caucus,D,NaN,caucus
1,HouseBlueDogs,no,"{'office': [{'id': 224685124, 'id_str': '22468...",house,NaN,Blue Dog Coalition,D,NaN,caucus
2,CAPAC,no,"{'office': [{'id': 192955168, 'id_str': '19295...",house,NaN,Congressional Asian Pacific American Caucus,D,NaN,caucus
3,OfficialCBC,no,"{'office': [{'id': 233783568, 'id_str': '23378...",house,NaN,Congressional Black Caucus,D,NaN,caucus
4,HealthCaucus,no,"{'office': [{'id': 20020575, 'id_str': '200205...",house,NaN,Congressional Health Caucus,R,NaN,caucus
5,ProChoiceCaucus,no,"{'office': [{'id': 809505942186455000, 'id_str...",house,NaN,Congressional Pro-Choice Caucus,D,NaN,caucus
6,USProgressives,no,"{'office': [{'id': 246088673, 'id_str': '24608...",house,NaN,Congressional Progressive Caucus,D,NaN,caucus
7,gopdoccaucus,no,"{'office': [{'id': 119899270, 'id_str': '11989...",house,NaN,GOP Doctors Caucus,R,NaN,caucus
8,HispanicCaucus,no,"{'office': [{'id': 33530012, 'id_str': '335300...",house,NaN,Hispanic Caucus,D,NaN,caucus
9,freedomcaucus,no,"{'office': [{'id': 2990729241, 'id_str': '2990...",house,NaN,House Freedom Caucus,R,NaN,caucus
10,conversations,no,"{'office': [{'id': 2990729241, 'id_str': '2990...",house,NaN,House Freedom Caucus,R,NaN,caucus
11,libertycaucus,no,"{'office': [{'id': 426862142, 'id_str': '42686...",house,NaN,House Liberty Caucus,R,NaN,caucus
12,LGBTEqCaucus,no,"{'office': [{'id': 1392282998, 'id_str': '1392...",house,NaN,LGBT Equality Caucus,D,NaN,caucus
13,RepublicanStudy Committee,no,"{'office': [{'id': 22528309, 'id_str': '225283...",house,NaN,Republican Study,R,NaN,caucus
14,LadiesGOP,no,"{'office': [{'id': 1322558402, 'id_str': '1322...",house,NaN,Republican Women's Policy Committee,R,NaN,caucus
15,repdonyoung,no,"{'office': [{'id': 37007274, 'id_str': '370072...",house,"{'bioguide': 'Y000033', 'govtrack': 400440}",Don Young,R,AK,member
16,DonYoungAK,yes,"{'office': [{'id': 37007274, 'id_str': '370072...",house,"{'bioguide': 'Y000033', 'govtrack': 400440}",Don Young,R,AK,member
17,RepByrne,no,"{'office': [{'id': 2253968388, 'id_str': '2253...",house,"{'bioguide': 'B001289', 'govtrack': 412601}",Bradley Byrne,R,AL,member
18,BradleyByrne,yes,"{'office': [{'id': 2253968388, 'id_str': '2253...",house,"{'bioguide': 'B001289', 'govtrack': 412601}",Bradley Byrne,R,AL,member
19,USRepGaryPalmer,no,"{'office': [{'id': 2861616083, 'id_str': '2861...",house,"{'bioguide': 'P000609', 'govtrack': 412608}",Gary Palmer,R,AL,member
20,Palmer4Alabama,yes,"{'office': [{'id': 2861616083, 'id_str': '2861...",house,"{'bioguide': 'P000609', 'govtrack': 412608}",Gary Palmer,R,AL,member
21,RepMarthaRoby,no,"{'office': [{'id': 224294785, 'id_str': '22429...",house,"{'bioguide': 'R000591', 'govtrack': 412394}",Martha Roby,R,AL,member
22,TeamRoby,yes,"{'office': [{'id': 224294785, 'id_str': '22429...",house,"{'bioguide': 'R000591', 'govtrack': 412394}",Martha Roby,R,AL,member
23,RepMikeRogersAL,no,"{'office': [{'id': 33977070, 'id_str': '339770...",house,"{'bioguide': 'R000575', 'govtrack': 400341}",Mike Rogers,R,AL,member
24,MikeRogersCamp,yes,"{'office': [{'id': 33977070, 'id_str': '339770...",house,"{'bioguide': 'R000575', 'govtrack': 400341}",Mike Rogers,R,AL,member
25,RepMoBrooks,no,"{'office': [{'id': 237299871, 'id_str': '23729...",house,"{'bioguide': 'B001274', 'govtrack': 412395}",Mo Brooks,R,AL,member
26,Robert_Aderholt,no,"{'office': [{'id': 76452765, 'id_str': '764527...",house,"{'bioguide': 'A000055', 'govtrack': 400004}",Robert Aderholt,R,AL,member
27,CongAderholt,yes,"{'office': [{'id': 76452765, 'id_str': '764527...",house,"{'bioguide': 'A000055', 'govtrack': 400004}",Robert Aderholt,R,AL,member
28,RepTerriSewell,no,"{'office': [{'id': 381152398, 'id_str': '38115...",house,"{'bioguide': 'S001185', 'govtrack': 412396}",Terri Sewell,D,AL,member
29,RepWesterman,no,"{'office': [{'id': 2852998461, 'id_str': '2852...",house,"{'bioguide': 'W000821', 'govtrack': 412610}",Bruce Westerman,R,AR,member
...,...,...,...,...,...,...,...,...,...
977,SenTedCruz,no,"{'office': [{'id': 1074480192, 'id_str': '1074...",senate,"{'bioguide': 'C001098', 'govtrack': 412573}",Ted Cruz,R,TX,member
978,TeamTedCruz,yes,"{'office': [{'id': 1074480192, 'id_str': '1074...",senate,"{'bioguide': 'C001098', 'govtrack': 412573}",Ted Cruz,R,TX,member
979,tedcruz,yes,"{'office': [{'id': 1074480192, 'id_str': '1074...",senate,"{'bioguide': 'C001098', 'govtrack': 412573}",Ted Cruz,R,TX,member
980,SenMikeLee,no,"{'office': [{'id': 88784440, 'id_str': '887844...",senate,"{'bioguide': 'L000577', 'govtrack': 412495}",Mike Lee,R,UT,member
981,MikeLeeforUtah,yes,"{'office': [{'id': 88784440, 'id_str': '887844...",senate,"{'bioguide': 'L000577', 'govtrack': 412495}",Mike Lee,R,UT,member
982,senorrinhatch,no,"{'office': [{'id': 262756641, 'id_str': '26275...",senate,"{'bioguide': 'H000338', 'govtrack': 300052}",Orrin Hatch,R,UT,member
983,OrrinHatch,yes,"{'office': [{'id': 262756641, 'id_str': '26275...",senate,"{'bioguide': 'H000338', 'govtrack': 300052}",Orrin Hatch,R,UT,member
984,MarkWarner,no,"{'office': [{'id': 7429102, 'id_str': '7429102...",senate,"{'bioguide': 'W000805', 'govtrack': 412321}",Mark Warner,D,VA,member
985,SenKaineOffice,no,"{'office': [{'id': 1267940407, 'id_str': '1267...",senate,"{'bioguide': 'K000384', 'govtrack': 412582}",Tim Kaine,D,VA,member
986,timkaine,no,"{'office': [{'id': 1267940407, 'id_str': '1267...",senate,"{'bioguide': 'K000384', 'govtrack': 412582}",Tim Kaine,D,VA,member
987,SenSanders,no,"{'office': [{'id': 29442313, 'id_str': '294423...",senate,"{'bioguide': 'S000033', 'govtrack': 400357}",Bernie Sanders,I,VT,member
988,BernieSanders,yes,"{'office': [{'id': 29442313, 'id_str': '294423...",senate,"{'bioguide': 'S000033', 'govtrack': 400357}",Bernie Sanders,I,VT,member
989,SenatorLeahy,no,"{'office': [{'id': 242836537, 'id_str': '24283...",senate,"{'bioguide': 'L000174', 'govtrack': 300065}",Patrick Leahy,D,VT,member
990,PatrickLeahy,yes,"{'office': [{'id': 242836537, 'id_str': '24283...",senate,"{'bioguide': 'L000174', 'govtrack': 300065}",Patrick Leahy,D,VT,member
991,SenatorCantwell,no,"{'office': [{'id': 117501995, 'id_str': '11750...",senate,"{'bioguide': 'C000127', 'govtrack': 300018}",Maria Cantwell,D,WA,member
992,MariaCantwell,yes,"{'office': [{'id': 117501995, 'id_str': '11750...",senate,"{'bioguide': 'C000127', 'govtrack': 300018}",Maria Cantwell,D,WA,member
993,PattyMurray,no,"{'office': [{'id': 293131808, 'id_str': '29313...",senate,"{'bioguide': 'M001111', 'govtrack': 300076}",Patty Murray,D,WA,member
994,MurrayCampaign,yes,"{'office': [{'id': 293131808, 'id_str': '29313...",senate,"{'bioguide': 'M001111', 'govtrack': 300076}",Patty Murray,D,WA,member
995,SenRonJohnson,no,"{'office': [{'id': 233737858, 'id_str': '23373...",senate,"{'bioguide': 'J000293', 'govtrack': 412496}",Ron Johnson,R,WI,member
996,RonJohnsonWI,yes,"{'office': [{'id': 233737858, 'id_str': '23373...",senate,"{'bioguide': 'J000293', 'govtrack': 412496}",Ron Johnson,R,WI,member
997,SenatorBaldwin,no,"{'office': [{'id': 1074518754, 'id_str': '1074...",senate,"{'bioguide': 'B001230', 'govtrack': 400013}",Tammy Baldwin,D,WI,member
998,tammybaldwin,yes,"{'office': [{'id': 1074518754, 'id_str': '1074...",senate,"{'bioguide': 'B001230', 'govtrack': 400013}",Tammy Baldwin,D,WI,member
999,Sen_JoeManchin,no,"{'office': [{'id': 234374703, 'id_str': '23437...",senate,"{'bioguide': 'M001183', 'govtrack': 412391}",Joe Manchin,D,WV,member
1000,JoeManchinWV,yes,"{'office': [{'id': 234374703, 'id_str': '23437...",senate,"{'bioguide': 'M001183', 'govtrack': 412391}",Joe Manchin,D,WV,member
1001,SenCapito,no,"{'office': [{'id': 193794406, 'id_str': '19379...",senate,"{'bioguide': 'C001047', 'govtrack': 400061}",Shelley Moore Capito,R,WV,member
1002,CapitoforWV,yes,"{'office': [{'id': 193794406, 'id_str': '19379...",senate,"{'bioguide': 'C001047', 'govtrack': 400061}",Shelley Moore Capito,R,WV,member
1003,SenJohnBarrasso,no,"{'office': [{'id': 202206694, 'id_str': '20220...",senate,"{'bioguide': 'B001261', 'govtrack': 412251}",John Barrasso,R,WY,member
1004,barrassoforwyo,yes,"{'office': [{'id': 202206694, 'id_str': '20220...",senate,"{'bioguide': 'B001261', 'govtrack': 412251}",John Barrasso,R,WY,member
1005,SenatorEnzi,no,"{'office': [{'id': 291756142, 'id_str': '29175...",senate,"{'bioguide': 'E000285', 'govtrack': 300041}",Mike Enzi,R,WY,member
1006,EnziforWyo,yes,"{'office': [{'id': 291756142, 'id_str': '29175...",senate,"{'bioguide': 'E000285', 'govtrack': 300041}",Mike Enzi,R,WY,member

In [46]:
final = pd.concat([df7, df1, party])

In [47]:
final.head()

,accounts,ch,chamber,id,name,party,screen_name,state,type
0,"{'office': [{'id': 817097052375187500, 'id_str...",no,house,NaN,Blue Collar Caucus,D,BlueCollarDems,NaN,caucus
1,"{'office': [{'id': 224685124, 'id_str': '22468...",no,house,NaN,Blue Dog Coalition,D,HouseBlueDogs,NaN,caucus
2,"{'office': [{'id': 192955168, 'id_str': '19295...",no,house,NaN,Congressional Asian Pacific American Caucus,D,CAPAC,NaN,caucus
3,"{'office': [{'id': 233783568, 'id_str': '23378...",no,house,NaN,Congressional Black Caucus,D,OfficialCBC,NaN,caucus
4,"{'office': [{'id': 20020575, 'id_str': '200205...",no,house,NaN,Congressional Health Caucus,R,HealthCaucus,NaN,caucus

In [48]:
final.shape

(1077, 9)

In [49]:
final.to_csv("split_meta.csv", encoding='utf-8')